#!/bin/bash
# Build CatcherVsRunner.app — a hand-rolled macOS .app bundle that
# launches the game by double-click without a Terminal window.
#
# Run once from the project root:
#   bash build_app.sh
#
# The resulting CatcherVsRunner.app is relocatable (move it to ~/Desktop
# or /Applications and it still works) because the project's absolute
# path is baked into the launcher at build time. If the project itself
# moves, rerun this script.
#
# Requires: an existing python3 with `pygame` and `numpy` installed
# (the system /usr/bin/env python3 is used at launch).

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP="${PROJECT_DIR}/CatcherVsRunner.app"
CONTENTS="${APP}/Contents"
MACOS="${CONTENTS}/MacOS"
LAUNCHER="${MACOS}/CatcherVsRunner"

rm -rf "${APP}"
mkdir -p "${MACOS}"

cat > "${CONTENTS}/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>CatcherVsRunner</string>
  <key>CFBundleIdentifier</key>
  <string>com.catcher-vs-runner.local</string>
  <key>CFBundleName</key>
  <string>Catcher vs. Runner</string>
  <key>CFBundleDisplayName</key>
  <string>Catcher vs. Runner</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1</string>
  <key>LSMinimumSystemVersion</key>
  <string>10.13</string>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
PLIST

cat > "${LAUNCHER}" <<EOF
#!/bin/bash
# Auto-generated by build_app.sh. Project path baked in below.
cd "${PROJECT_DIR}" || exit 1
exec /usr/bin/env python3 -m catcher_vs_runner
EOF
chmod +x "${LAUNCHER}"

echo "Built ${APP}"
echo "Double-click it from Finder, or run: open '${APP}'"
